![NYC Skyline](nyc.jpg)

Welcome to New York City, one of the most-visited cities in the world. There are many Airbnb listings in New York City to meet the high demand for temporary lodging for travelers, which can be anywhere between a few nights to many months. In this project, we will take a closer look at the New York Airbnb market by combining data from multiple file types like `.csv`, `.tsv`, and `.xlsx`.

Recall that **CSV**, **TSV**, and **Excel** files are three common formats for storing data. 
Three files containing data on 2019 Airbnb listings are available to you:

**data/airbnb_price.csv**
This is a CSV file containing data on Airbnb listing prices and locations.
- **`listing_id`**: unique identifier of listing
- **`price`**: nightly listing price in USD
- **`nbhood_full`**: name of borough and neighborhood where listing is located

**data/airbnb_room_type.xlsx**
This is an Excel file containing data on Airbnb listing descriptions and room types.
- **`listing_id`**: unique identifier of listing
- **`description`**: listing description
- **`room_type`**: Airbnb has three types of rooms: shared rooms, private rooms, and entire homes/apartments

**data/airbnb_last_review.tsv**
This is a TSV file containing data on Airbnb host names and review dates.
- **`listing_id`**: unique identifier of listing
- **`host_name`**: name of listing host
- **`last_review`**: date when the listing was last reviewed

## Objective

As a consultant working for a real estate start-up, you have collected Airbnb listing data from various sources to investigate the short-term rental market in New York. You'll analyze this data to provide insights on private rooms to the real estate company.

There are three files in the `data` folder: `airbnb_price.csv`, `airbnb_room_type.xlsx`, `airbnb_last_review.tsv`.

- What are the dates of the earliest and most recent reviews? Store these values as two separate variables with your preferred names.

- How many of the listings are private rooms? Save this into any variable.

- What is the average listing price? Round to the nearest two decimal places and save into a variable.

- Combine the new variables into one DataFrame called `review_dates` with four columns in the following order: `first_reviewed`, `last_reviewed`, `nb_private_rooms`, and `avg_price`. The DataFrame should only contain one row of values.

In [3]:
# Import necessary packages
import pandas as pd
import numpy as np

In [4]:
# Loading files
df_price = pd.read_csv('data/airbnb_price.csv')
df_room_type = pd.read_excel('data/airbnb_room_type.xlsx')
df_last_review = pd.read_csv('data/airbnb_last_review.tsv', sep='\t')

# Merging the DataFrames
merged_df = pd.merge(df_price, df_room_type, on='listing_id')
merged_df = pd.merge(merged_df, df_last_review, on='listing_id')

In [5]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25209 entries, 0 to 25208
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   listing_id   25209 non-null  int64
 1   price        25209 non-null  object
 2   nbhood_full  25209 non-null  object
 3   description  25199 non-null  object
 4   room_type    25209 non-null  object
 5   host_name    25201 non-null  object
 6   last_review  25209 non-null  object
dtypes: int64(1), object(6)
memory usage: 1.3+ MB

In [6]:
# Displaying the first rows of the merged DataFrame
merged_df.head()

,listing_id,price,nbhood_full,description,room_type,host_name,last_review
0,2595,225 dollars,"Manhattan, Midtown",Skylit Midtown Castle,Entire home/apt,Jennifer,May 21 2019
1,3831,89 dollars,"Brooklyn, Clinton Hill",Cozy Entire Floor of Brownstone,Entire home/apt,LisaRoxanne,July 05 2019
2,5099,200 dollars,"Manhattan, Murray Hill",Large Cozy 1 BR Apartment In Midtown East,Entire home/apt,Chris,June 22 2019
3,5178,79 dollars,"Manhattan, Hell's Kitchen",Large Furnished Room Near B'way,private room,Shunichi,June 24 2019
4,5238,150 dollars,"Manhattan, Chinatown",Cute & Cozy Lower East Side 1 bdrm,Entire home/apt,Ben,June 09 2019

In [7]:
merged_df['last_review'] = pd.to_datetime(merged_df['last_review'])

In [8]:
last_reviewed = merged_df['last_review'].max()
first_reviewed = merged_df['last_review'].min()
print(f'The first date record is {first_reviewed} and the last record is {last_reviewed}')

The first date record is 2019-01-01 00:00:00 and the last record is 2019-07-09 00:00:00

In [9]:
merged_df['room_type'] = merged_df['room_type'].str.lower()
private_rooms = merged_df[merged_df['room_type'] == 'private room']
nb_private_rooms = len(private_rooms)
print(f'There are {nb_private_rooms} private rooms')

There are 11356 private rooms

In [10]:
merged_df['price'] = merged_df['price'].astype(str).str.replace('dollars', '').astype(float)
average_price = merged_df['price'].mean()
avg_price = round(average_price, 2)
print(f"Average listing price rounded to two decimal places: {avg_price}")

Average listing price rounded to two decimal places: 141.78

In [11]:
review_dates_dict = {'first_reviewed': [first_reviewed],
                     'last_reviewed': [last_reviewed],
                     'nb_private_rooms': [nb_private_rooms],
                     'avg_price': [avg_price]}
review_dates = pd.DataFrame(review_dates_dict)
review_dates.head()

  first_reviewed last_reviewed  nb_private_rooms  avg_price
0     2019-01-01    2019-07-09             11356     141.78